### ISSUE TITLE
Hacktoberfest 2021

### ISSUE THREAD

**Issue by ocefpaf** [juoceano/lecture_figures#22]
@xeulha e @jojobozz vamos usar esse *issue* aqui para coordenar o Hacktoberfest. A primeiramente PR será adicionar um pacote ao conda-forge. Peguei uma lista aqui de pacotes com temas de oceanografia que não tem no conda-forge e podemos adicionar. Se conhecerem algum outro podemos colocar na lista também:

- [x] https://pypi.org/project/mlo-co2
- [x] https://pypi.org/project/pyTEF
- [x] https://pypi.org/project/freshwater
- [x] https://pypi.org/project/lakepy
- [x] https://pypi.org/project/ctdcal

Corrigir documentação do erddapy:
- [ ] notebook 03-advanced_search.ipynb
- [ ] pacotes opcionais não documentados

**Comment by ocefpaf** [comment]
1. Primeiramente vocês tem que ir no https://github.com/conda-forge/staged-recipes e fazer um "fork" do repositório.

![FORK](https://user-images.githubusercontent.com/950575/136080025-09119968-76b0-4e01-ba3c-4f7e0cec6032.png)


2. Quando o fork estiver pronto vocês tem uma "cópia" do repositório. Agora vamos ver se temos os programas que vamos precisar instalados. Primeiramente chequem se tem o `conda` com:

```shell
which conda  # Linux e macOS
# ou 
where conda # Windows
```

Se isso mostrar o conda vocês podem executar os seguintes comandos para criar um ambiente para o hacktoberfest:

```
conda create --name HACK python=3.9 git gh grayskull codespell --yes
conda activate HACK
```

Daí, dentro de algum diretório/pasta de trabalho que vocês sabem localizar facilmente digitem:

```
gh repo clone SEU-GITHUB-HANDLE/staged-recipes # Note que aqui vocês tem que mudar o `SEU-GITHUB-HANDLE` para xeulha ou jojobozz
```

Quando terminarem essa parte me avisa que passo o resto. Qualquer problema vamos nos falando por aqui ou pelo telegram.

**Comment by xeulha** [comment]
Oi, @ocefpaf! Então, quando eu tento checar se tenho o conda aparece isso.
<img width="585" alt="Captura de Tela 2021-10-06 às 16 28 07" src="https://user-images.githubusercontent.com/91758546/136270461-10d0de2b-a240-4814-8b12-1e2801123522.png">
Não sei o que isso quer dizer ou o que preciso fazer, socorro 
P.S.: Não sei se estou usando o git do jeito certo pra falar isso kkkkkkk

**Comment by juoceano** [comment]
@xeulha você está a usando da forma correta sim...eu é que não estava (tanto que ao tentar de te responder fechei o issue sem querer hehehe).

**Comment by jojobozz** [comment]
Consegui realizar toda a criação do ambiente e adicionar a cópia do repositório, mas para a instalação das bibliotecas dentro do ambiente tive que fazer um por um utilizando o "conda install -c conda-forge oquequeriainstalar" não sei se isso muda alguma coisa, não entendo bem porque algumas bibliotecas instalam só fazendo "conda install ..." e outras precisam de "conda install -c conda-forge"
 
![image](https://user-images.githubusercontent.com/68918390/136313308-32570887-34ed-4791-96e3-9cdf624ba005.png)

**Comment by ocefpaf** [comment]
> Oi, @ocefpaf! Então, quando eu tento checar se tenho o conda aparece isso.

Isso é uma função que "aponta" para o conda. Digita:

```
conda --version
```

Para ter certeza que ele funciona. Você vai ver a versão do conda instalado. Daí é só seguir as instruções acime. Qualquer coisa vai perguntando aqui.

**Comment by ocefpaf** [comment]
> Consegui realizar toda a criação do ambiente e adicionar a cópia do repositório, mas para a instalação das bibliotecas dentro do ambiente tive que fazer um por um utilizando o "conda install -c conda-forge oquequeriainstalar" não sei se isso muda alguma coisa, não entendo bem porque algumas bibliotecas instalam só fazendo "conda install ..." e outras precisam de "conda install -c conda-forge"

Eu uso o conda-forge no dia-a-dia tão frequentemente que esqueço essa parte. Inclusive eu recomendo a vocês duas (@jojobozz e @xeulha) a digitar os seguintes comandos para configurar o conda-forge permanentemente na instalação de vocês:

```shell
conda config --add channels conda-forge
conda config --set channel_priority strict
conda config --remove channels defaults
```

Daí não precisa mas do `-c conda-forge` pq tudo vai vir do conda-forge.

PS0: conda-forge é um canal de pacotes da comunidade. É mais ágil e tem mais pacotes que o "defaults" e a primeira PR de vocês vai ser exatamente adicionar um pacote lá.

PS1: @jojobozz você tá pronta para o próximo passo mas vamos esperar a @xeulha chegar no mesmo ponto para mandar os próximos passos.

**Comment by xeulha** [comment]
Eu fiz as instalções uma por uma que nem a @jojobozz e aí na hora de fazer a última parte aconteceram 2 coisas.
A 1ª foi a seguinte: 
![image](https://user-images.githubusercontent.com/91758546/136463831-43ab5f19-8e86-4893-b5c8-b04021b13d5e.png)
Não consegui porque fico recebendo ¨permission denied¨ quando tento acessar a pasta que quero usar. 
Aí tentei arrumar mudando as configurações de privacidade do computador, mas não resolveu, aí a segunda coisa que aconteceu foi que resolvi fazer algo que talvez não seja o correto:
<img width="679" alt="Captura de Tela 2021-10-07 às 18 21 40" src="https://user-images.githubusercontent.com/91758546/136464048-e78e8b23-bfcd-425e-acb8-de0366fdc25d.png">
Aí usando esse procedimento consegui fazer o último passo.
![image](https://user-images.githubusercontent.com/91758546/136465011-dc1195fa-b6da-4948-80e8-5ddb72daf69c.png)

**Comment by ocefpaf** [comment]
@xeulha eu não entendo de macOSes mas acho que você conseguiu resolver. Agora que tem um *fork* local do staged-recipes aqui vão os próximos passos.

- ative o ambiente HACK: `conda activate HACK`
- Leiam essa parte da lição de git do Software Carpentry e configure o git para o seu username e email.

https://swcarpentry.github.io/git-novice/02-setup/index.html

(Se tiverem um tempo vale a pena ler tudo!)

- entre no diretório recipes: `cd staged-recipes/recipes/` da sua cópia (fork) local
- com o grayskull você vão criar uma receita para os pacotes acima da seguinte forma,

```
grayskull pypi mlo-co2 # @xeulha 
grayskull pypi pyTEF # @jojobozz 
```

Você vão notar que esse comando vai criar uma pasta nova com a receita para esses pacotes. Precisamo criar uma PR com essas pastas. O "workflow" mais comum do GitHub é: `fork` (vocês já fizeram), `branch`, e `PR`. Para criar um branch vocês digitam,

```
git checkout -b mlo-co2  # @xeulha 
git checkout -b pyTEF # @jojobozz 
```

Pronto! Criamos um branch para cada uma com o nome do pacote. Agora temos que adicionar a pasta para o git começar a "tracker" esses arquivos:

```
git add mlo-co2  # @xeulha 
git add pyTEF # @jojobozz 
```

O `add` só fala pro git começar a "trackear" as mudanças. Como não vamos modificar mais nada podemos fazer o `commit` e o `push`, que significa "gravar as mudanças" e mandá-las para a seu fork no GitHub:

```
git commit mlo-co2 -m "add mlo-co2"  # @xeulha 
git commit pyTEF -m "add pyTEF" # @jojobozz 
```

A opção `-m` passa uma mensagem para o `commit`. E finalmente vamos mandar as mudanças para o GitHub com:

```
git push --set-upstream origin mlo-co2  # @xeulha
git push --set-upstream origin pyTEF # @jojobozz
```

Notem que eu mantive o nome do branch e a mensagem de commit com o nome do pacote para facilitar, mas podem ser diferentes. Branch é o contexto da alteração que vão fazer e a mensagem do commit uma descrição desse contexto. Se tudo der certo vocês vão ver uma tela assim:

![push](https://user-images.githubusercontent.com/950575/136596403-6b7aa219-6a6f-4012-a572-30d741c3071b.png)

Cliquem no link, escrevam uma mensagem como: "Adding package named X, ping @ocefpaf`, criem a PR no botão de baixo à direita, e eu vou fazer a revisão/merge da PR de vocês.

PS0: tem muitos passos e muita informação "omitida" aqui! Vamos devagar tentando resolver os problemas/dúvidas aos poucos e se precisar a gente marca uma sessão de vídeo para fazermos juntos. Mas depois que isso funcionar as outras serão mais do mesmo.

PS1: Chequem o que são esses pacotes nos links lá do primeiro comentário. Coloquei pacotes de oceanografia mais por curiosidade.

**Comment by jojobozz** [comment]
Oi! O passo a passo correu bem, a PR enviada tá aqui: conda-forge/staged-recipes/pull/16442, mas pelo visto deu erro no check (nao sei o que significa kkk) aguardo as próximas instruções

![image](https://user-images.githubusercontent.com/68918390/136642153-0981fa9d-a662-44d3-9627-267456a7613e.png)

**Comment by xeulha** [comment]
Oie! Aqui também o passo a passo foi tranquilo, cheguei nisso: 
![image](https://user-images.githubusercontent.com/91758546/136818385-4f5fb922-4dd7-434d-98eb-6ef33fe403d0.png)
Mas também tive esse problema que a Juana teve:
![image](https://user-images.githubusercontent.com/91758546/136818465-42b73097-0122-44fe-bb24-9e768b7d1d37.png)

**Comment by ocefpaf** [comment]
As duas PRs deram certo mas a da @xeulha eu tive que fechar por um problema no pacote. Agora, ambas vocês tem que fazer o seguinte para mandar o próximo, tudo dentro da pasta do repositório:

```shell
git checkout main  # sai do branch que criaram e volta para o main
git fetch upstream  # para atualizar o fork de vocês com as últimas alterações do "upstream"
git merge upstream/main  # faz o "merge" das alterções acima no seu main local
```

Depois desses 3 comandos é só repetir os passos acima mas para outro pacote.

@jojobozz você pode fazer o `ctdcal` e a @xeulha os `freshwater` e `lakepy` (um por vez para não complicar).

PS0: quando for dar o "ping" no meu username coloquem no corpo da mensagem senão eu não recebo a notificação.
PS1: os passos são bem complicados e eu esperava que vocês se complicasse mais! Primeiramente parabéns pela esperteza em se virar com instruções quebradas e complexas! Segundamente temos que marcar uma ligação para eu explicar melhor o que estamos fazendo.

**Comment by xeulha** [comment]
@ocefpaf não sei se entendi direito essa última parte, mas eu fiz o checkout na pasta do mlo-co2 e aí não rolou de fazer os outros dois, apareceu isso 
![image](https://user-images.githubusercontent.com/91758546/136984253-f74cd6af-bc8d-4e2a-a678-638bddda1823.png)
aí eu tentei fazer na pasta recipes e deu isso 
![image](https://user-images.githubusercontent.com/91758546/136984343-5f625c61-8353-40ca-b6f7-43ebf81a8996.png)
não sei se fiz o que era pra ser feito ou se era pra ser feito na pasta staged-recipes ou na própria pasta Hacktober, resumindo fiquei confusa.

**Comment by ocefpaf** [comment]
> não sei se fiz o que era pra ser feito ou se era pra ser feito na pasta staged-recipes ou na própria pasta Hacktober, resumindo fiquei confusa.

Na primeira vez não funcionou pq a pasta `mlo-co2` só existia dentro do branch `mlo-co2`. Quando você saiu do branch de volta para o `main` e como se tivesse removido o chão de onde estava com você encima. (Coisas de `git`... Aos poucos você vai descobrindo todas as idiosincrasias dele.)

Na segunda funcionou pq agora você estava em uma pasta que "existia" no `main`. Para evitar ser pega de surpresa por isso façam tudo da pasta `recipes`.

**Comment by xeulha** [comment]
Oi, Filipe! Tentei fazer aqui pro [freshwater](https://github.com/conda-forge/staged-recipes/pull/16498) e pro [lakepy](https://github.com/conda-forge/staged-recipes/pull/16499) e acho que deu certo (apesar de eu sentir que não deu).
![image](https://user-images.githubusercontent.com/91758546/137003040-3d9470bb-efcb-4c5a-ba4a-9defb36f5631.png)
![image](https://user-images.githubusercontent.com/91758546/137003081-78ffd8f0-b831-4393-8d62-2689f92f0c6a.png)

**Comment by jojobozz** [comment]
Acho que deu tudo certo aqui também, e acho que entendi meu erro na primeira PR eu apliquei os comandos na pasta staged-recipes, mas não dentro da pasta recipes 

![image](https://user-images.githubusercontent.com/68918390/137054729-2fa9e36d-3270-4b03-b5c2-003fa1b97b30.png)

O link da PR tá aqui: https://github.com/conda-forge/staged-recipes/pull/16502

**Comment by ocefpaf** [comment]
:tada: 

OK. Duas PRs adicionando pacotes! Um pouco do pq estamos fazendo isso. Vocês já devem ter percebido que para Python com aplicações científicas usar o `pip`, que é *default* no Python, vai acabar nos limitando. Por isso que a comunidade criou o conda. Mas até mesmo o canal *default*, curado pela empresa AnacondaInc, nos limita pq eles não conseguem adicionar todos os pacotes que os cientistas precisam.

Surge o conda-forge. Ao invés de cada usuário adicionar em seu canal pessoal o conda-forge é uma iniciativa de fazer isso como comunidade. Então, sempre que vocês tiverem algum problemas para instalar algo vocês podem perguntar nos canais de ajuda do conda-forge para tentar resolver o problema. Desde adicionar um pacote que não estava lá, até resolver problemas com pacotes existentes. O principal lugar para fazer perguntas é: https://gitter.im/conda-forge/conda-forge.github.io

**Comment by ocefpaf** [comment]
Próximos passos... PRs para resolver problemas na documentação! O staged-recipes é um repositório do GitHub do conda-forge, onde a gente adiciona pacotes. Mas não é algo muito interessante para além de adicionar pacotes que podemos precisar.

Entretando o GitHub está cheio de código fonte das bibliotecas que usamos no nosso dia-a-dia. Uma que eu mantenho para o meu emprego é a `erddapy`: https://github.com/ioos/erddapy

Eu acabei de adicionar um notebook lá mas não fiz a revisão do texto e por ter uns probleminhas nele.
Vocês vão, assim como fizeram com o stage-recipes:

- ativar o ambiente HACK `conda activate HACK`
- instalar o jupyter com `conda install jupyter --yes` para poder abrir o notebook
- fazer um fork do repositório https://github.com/ioos/erddapy a partir do mesmo diretório `hacktober` que vocês criaram
- entrar no diretório `cd erddapy/notebooks`
- abrir o jupyter com `jupyter notebook` e clicar no notebook `03-advanced_search.ipynb`.

No notebook vocês vão fazer algo super importante mas que ninguém quer fazer: revisar a documentação!
Leiam, façam edições de sugestões, tem uns errinhos (typos) em algumas células e, se acharem, corrijam eles. Depois mandem uma PR com o que fizerem. Lembrem que para mandar a PR temos que:

- fazer um branch com `git checkout -b notebook_review`
- editar o notebook
- fazer o commit das mudanças com `git commit 03-advanced_search.ipynb -m "fixed typo`

A mensagem de commit acima é uma sugestão. Se vocês fizerem modificações para melhorar o texto coloquem algo com "`-m clarified something blahblahblah`. Escrever mensagens de commit é uma arte. Elas tem que ser curtas mas informativas. Lembrem que vocês semana que vem já não sabe o que fizeram, mas a história do git guardou a mensagem para podermos checar no futuro o que fizemos.

Novamente, tem muitos passos ali e pouco contexto mas vão perguntam qq coisa e vamos nos comunicando por aqui.

**Comment by jojobozz** [comment]
Boa noite, não sei se entendi esse passo:

- " fazer um fork do repositório https://github.com/ioos/erddapy a partir do mesmo diretório hacktober que vocês criaram "

Quando fizemos o fork do staged-recipes só apertei no botão fork, como seria pra fazer esse fork a partir do diretório? Seria pra fazer um clone do repositório no diretório depois com os comandos:

`gh repo clone SEU-GITHUB-HANDLE/erddapy`

**Comment by ocefpaf** [comment]
Isso mesmo! Ainda bem que você entende as minhas instruções tortas escritas com muito sono!

**Comment by jojobozz** [comment]
Perfeito! Agora fiquei com um questionamento, tudo que eu fizer no jupyter notebook não vai alterar o original né? somente a cópia que eu tenho no meu computador e github isso?

**Comment by ocefpaf** [comment]
Pessoal, indo para a última atividade do hacktoberfest.

@xeulha para você pensei em um "typo fixing" mais hardcore. O projeto https://github.com/euroargodev/argopy é um módulo Python para obtenção de dados do [boias flutuantes argo](https://argo.ucsd.edu/). Vamos começar como sempre fazendo o *fork* e um clone local. Daí vamos criar um branch `fix_typos` mas ao invés de procurar eles vamos usar uma ferramenta automatizada para checar, o codespell!

De dentro da pasta do seu clone do argopy, com o ambiente `HACK` ativado, digite:

```
codespell docs --skip "*.css,*.ipynb"
```

 e você verá um output mais ou menos assim:

```
docs/contributing.rst:418: pres ==> press
docs/contributing.rst:418: pres ==> press
docs/why.rst:32: confortable ==> comfortable
docs/why.rst:36: wether ==> weather, whether
docs/what_is_argo.rst:25: fullfill ==> fulfill, fulfil
docs/whats-new.rst:204: usefull ==> useful
docs/whats-new.rst:208: recommand ==> recommend
docs/paper.md:86: softwares ==> software
```

Esse é a lista de error que o codespell encontrou. Alguns não são erros, como `pres` é a variável para pressão e não a palavra press. Outros você terá que ler a frase para ter um contexto, como o erro **wether**, a pessoa quis dizer *weather*, *whether*? Só lendo...

A lista é o nome do arquivo e a linha com o erro está. Abra o arquivo com o seu leitor de text favorito, navega até a linha, e corrija. Quando acabar todos você terá mais de um arquivo para dar "commit" algo que não fizemos até agora. Você pode fazer múltiplos commits, tipo `git commit docs/paper.md -m "fixed file docs/paper.md` ou fazer da pasta toda em um único commit com:

```
git commit docs/ -m "fixe typos in the docs folder"
```

PS0: no comando de checar os typos, `codespell docs --skip "*.css,*.ipynb"`, a gente só checou a pasta `docs` e pulo arquivos css (configuração da página web da documentação) e notebooks (só pq seria um pouco mais complicado). Mas se você estiver se sentindo aventureira você pode digitar: `codespell` sem essas opções e procurar typos em tudo! Vai ter muito falso positivo, então cuidado.

PS1: tenho acesso ao projeto do argo mas não é de minha autoria! Essa será a sua primeira contribuição "ao largo" para a comunidade! Os autores desse projeto são pessoas muito legais, vai tranquila que vão te ajudar no processo.

**Comment by ocefpaf** [comment]
@jojobozz para você tava pensando em resolver o issue: 

https://github.com/ioos/erddapy/issues/217

O idea é fazer no estilo *pair coding*. Podemos tentar marcar algo para semana que vem. Se acha que fica muito complicado podemos ver um isso que não vai precisar de ligação. Ah, e a @xeulha é mais do que convidada a participar e fazer o pair coding também.

**Comment by ocefpaf** [comment]
Pessoal. Ambas fizeram as 4 PRs e em breve devem receber o email da hacktoberfest. Espero que tenha plantado uma coceira para vocês aprenderem mais e, se um dia conseguirmos, vamos marcar um workshop na UFSC para trabalhar melhor essas ferramentas. Afinal de contas foi tudo corrido e tem muitos detalhes nas entrelinhas.

Abs e espero que tenham curtido!
